config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'', include('msg_board.board.urls', namespace='board')),

    url(settings.ADMIN_URL, admin.site.urls),

    url(r'^accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

msg_board/board/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.MessageListView.as_view(), name='home'),
    url(r'^comment/add/$', views.CommentCreateView.as_view(), name='comment_add'),
    url(r'^comment/(?P<pk>[^/]+)/edit/$', views.CommentUpdateView.as_view(), name='comment_edit'),
    url(r'^message/add/$', views.MessageCreateView.as_view(), name='message_add'),
    url(r'^message/(?P<pk>[^/]+)/edit/$', views.MessageUpdateView.as_view(), name='message_edit'),
]

msg_board/board/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf import settings
from django.db import models
from django.utils.translation import ugettext as _
from django.utils.encoding import python_2_unicode_compatible


class MessageAbstract(models.Model):
    """
    An abstract base class model for Message and Comment
    """
    text = models.TextField(verbose_name=_('Text'))
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Created by'))
    date_created = models.DateTimeField(auto_now_add=True, verbose_name=_('Date created'))
    date_updated = models.DateTimeField(auto_now=True, verbose_name=_('Date updated'))

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Message(MessageAbstract):
    def __str__(self):
        return 'Message {}'.format(self.text[:10])


@python_2_unicode_compatible
class Comment(MessageAbstract):
    """
    Comments could be attached to Message or Comment itself.
    msg used as thread of comments
    """
    msg = models.ForeignKey(Message)
    comment = models.ForeignKey('self', blank=True, null=True, related_name='comments')

    def __str__(self):
        return 'Comment {}'.format(self.text[:10])

msg_board/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class User(AbstractUser):

    def __str__(self):
        return self.username

msg_board/board/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django import forms
from django.utils.translation import ugettext as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout

from .models import Message, Comment


class MessageForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-inline tac'
        self.helper.form_action = 'board:message_add'
        self.helper.layout = Layout(
            'text',
            Submit('submit', _('Send'), css_class='btn btn-primary'),
        )

    class Meta:
        model = Message
        fields = ['text']
        labels = {
            'text': ''
        }
        widgets = {
            'text': forms.Textarea(attrs={
                'cols': 60,
                'rows': 5,
                'placeholder': _('Text message'),
                'required': True
            })
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text', 'msg', 'comment']

    def clean(self):
        cleaned_data = super(CommentForm, self).clean()

        # check that comment from correct thread(msg)
        if cleaned_data.get('comment') and cleaned_data['comment'].msg != cleaned_data['msg']:
            raise forms.ValidationError(_('Incorrect data'))

        return cleaned_data

msg_board/board/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import CreateView, UpdateView, ListView
from django.http import JsonResponse, Http404
from django.template.loader import render_to_string
from django.template import RequestContext
from django.shortcuts import redirect
from braces.views import LoginRequiredMixin

from .models import Message, Comment
from .forms import MessageForm, CommentForm


class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    def form_invalid(self, form):
        super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)


class MessageListView(ListView):
    model = Message
    template_name = 'board/home.html'
    context_object_name = 'msgs'
    paginate_by = settings.MESSAGE_PER_PAGE

    def get_context_data(self, **kwargs):
        context = super(MessageListView, self).get_context_data(**kwargs)
        context['form'] = MessageForm()

        msg_ids = [obj.id for obj in context['msgs']]
        # collect all needed comments by messages and by comments
        context['comments_all'] = {'by_message': {}, 'by_comment': {}}
        for obj in Comment.objects.select_related('created_by').filter(msg_id__in=msg_ids).order_by('date_created'):
            by_what = 'by_comment' if obj.comment_id else 'by_message'
            object_id = obj.comment_id or obj.msg_id

            if object_id not in context['comments_all'][by_what]:
                context['comments_all'][by_what][object_id] = []
            context['comments_all'][by_what][object_id].append(obj)

        return context

    def get_queryset(self):
        return Message.objects.select_related('created_by').order_by('-date_created')


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse('board:home')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(MessageCreateView, self).form_valid(form)

    def form_invalid(self, form):
        return redirect('board:home')


class MessageUpdateView(LoginRequiredMixin, AjaxableResponseMixin, UpdateView):
    model = Message
    fields = ['text']

    def get_success_url(self):
        return reverse('board:home')

    def get_object(self, queryset=None):
        obj = super(MessageUpdateView, self).get_object()
        if not obj.created_by_id == self.request.user.id:
            raise Http404
        return obj

    def form_valid(self, form):
        super(MessageUpdateView, self).form_valid(form)

        return JsonResponse({'text': self.object.text})


class CommentCreateView(LoginRequiredMixin, AjaxableResponseMixin, CreateView):
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        return reverse('board:home')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        super(CommentCreateView, self).form_valid(form)

        data = {
            'comment': render_to_string('snippets/msg.html', {
                'msg': self.object,
                'comments': []
            }, RequestContext(self.request))
        }

        return JsonResponse(data)


class CommentUpdateView(LoginRequiredMixin, AjaxableResponseMixin, UpdateView):
    model = Comment
    fields = ['text']

    def get_success_url(self):
        return reverse('board:home')

    def get_object(self, queryset=None):
        obj = super(CommentUpdateView, self).get_object()
        if not obj.created_by_id == self.request.user.id:
            raise Http404
        return obj

    def form_valid(self, form):
        super(CommentUpdateView, self).form_valid(form)

        return JsonResponse({'comment': self.object.text})

msg_board/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

msg_board/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}MsgBoard{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/jquery-editable.css' %}">
    <!-- This file stores project-specific CSS -->
    <link rel="stylesheet" href="{% static 'css/project.css' %}">

    {% block css %}{% endblock css %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">MsgBoard</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Placed at the end of the document so the pages load faster -->
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/tether.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>

      <script src="{% static 'js/jquery-editable-poshytip.min.js' %}"></script>
      <script src="{% static 'js/jquery.waypoints.js' %}"></script>
      <script src="{% static 'js/infinite.js' %}"></script>

    {% block javascript %}{% endblock javascript %}
  </body>
</html>

msg_board/templates/board/home.html
{% extends 'base.html' %}

{% load i18n crispy_forms_tags humanize board_tags %}

{% block content %}
    {% if request.user.is_authenticated %}
        {% crispy form %}
    {% else %}
        {% include 'account/login_buttons.html' %}
        <div class="text-xs-center">{% trans 'Please sign in to add messages and comments' %}</div>
    {% endif %}

    <div id="msg_board" class="row infinite-container">

        {% for msg in msgs %}
            {% render_msg msg comments_all.by_message|get:msg.pk %}
        {% endfor %}

    </div>

    <div class="loading" style="display: none;">
        {% trans 'Loading' %}...
    </div>

    {% if page_obj.has_next %}
        <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">{% trans 'More' %}</a>
    {% endif %}

{% endblock %}

{% block javascript %}
    <script>
        var csrf = "{% csrf_token %}".replace(/'/g, '"');

        function bind_editable() {
            $('.editable').editable({
                params: function(params) {
                    params[params['name']] = params['value'];
                    params["csrfmiddlewaretoken"] = $(csrf).val();
                    return params;
                },
                error: function(data) {
                    if (data.status != 400) {
                        return "{% trans 'Something went wrong' %}";
                    }
                    else{
                        var errors = $.parseJSON(data.responseText);
                        if(errors.text){
                            return errors.text[0];
                        }
                    }
                }
            });
        }

        function apply_form_field_error(form, fieldname, error) {
            var input = $(form).find("#id_" + fieldname),
                container = $(form).find("#div_id_" + fieldname),
                error_msg = $("<span />").addClass("form-control-feedback").html('<strong>'+error[0]+'</strong>');

            container.addClass("has-danger");
            input.addClass("form-control-danger");
            error_msg.insertAfter(input);
        }

        function clear_form_field_errors(form) {
            $(".form-control-feedback", $(form)).remove();
            $(".has-danger", $(form)).removeClass("error");
        }

        function reply_submit(form) {
            var self = $(form);
            var url = self.attr("action");
            clear_form_field_errors(form);
            $.ajax({
                url: url,
                type: "POST",
                data: self.serialize(),
                success: function(data) {
                    clear_form_field_errors(form);
                    $(form).find("#id_text").val('');
                    var thread = $(form).closest('.media-heading').next().find('.media-body')[0];
                    var comment = $("<div />").html(data.comment);
                    thread.append(comment[0]);

                    {# bind editable for just added messages #}
                    bind_editable();
                    bind_reply();
                },
                error: function(data) {
                    var errors = $.parseJSON(data.responseText);
                    $.each(errors, function(index, value) {
                        apply_form_field_error(self, index, value);
                    });
                }
            });
        }

        function bind_reply() {
            $('.reply_button').on('click', function () {
                var target = $(this).data('reply');
                var msg_id = $(this).data('msg');
                var comment_id = $(this).data('comment');

                if(!$('#' + target + ' .reply_form').length) {
                    $('#' + target).html('<form class="reply_form" action="{% url 'board:comment_add' %}" onsubmit="reply_submit(this);return false;">'+csrf+'<div id="div_id_text" class="form-group"><label for="id_text">{% trans 'Your Comment' %}</label><textarea required id="id_text" name="text" class="form-control" rows="3"></textarea></div><input type="hidden" name="msg" value="'+msg_id+'"><input type="hidden" name="comment" value="'+comment_id+'"><button type="submit" class="btn btn-primary">{% trans 'Send' %}</button></form>');
                }
            });
        }

        $(function() {
            //turn to inline mode
            $.fn.editable.defaults.mode = 'inline';
            bind_editable();
            bind_reply();

            var infinite = new Waypoint.Infinite({
                element: $('.infinite-container')[0],
                onBeforePageLoad: function () {
                    $('.loading').show();
                },
                onAfterPageLoad: function ($items) {
                    $('.loading').hide();
                    bind_editable();
                    bind_reply();
                }
            });

        });
    </script>
{% endblock javascript %}

msg_board/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

msg_board/templates/bootstrap4/layout/field_errors.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <span id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="form-control-feedback"><strong>{{ error }}</strong></span>
    {% endfor %}
{% endif %}

msg_board/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

msg_board/templates/snippets/msg.html
{% load i18n humanize %}
{% load board_tags %}

<div class="media {% if not msg.msg_id %}infinite-item{% endif %}">
    <div class="media-heading">
        {{ msg.created_by }} - {{ msg.date_created|naturaltime }}
        <p
          {% if request.user.pk == msg.created_by_id %}
              class="editable" data-type="textarea" data-name="text" data-pk="{{ msg.pk }}"
              {% if msg|classname == 'Message' %}
                  data-url="{% url 'board:message_edit' msg.pk %}"
              {% else %}
                  data-url="{% url 'board:comment_edit' msg.pk %}"
              {% endif %}
          {% endif %}
        >{{ msg.text }}</p>
        {% if request.user.is_authenticated %}
            <span>
                <a class="reply_button" data-reply="reply_comment{{ msg|classname }}{{ msg.pk }}" role="button" data-toggle="collapse" href="#reply_comment{{ msg|classname }}{{ msg.pk }}" aria-expanded="false" aria-controls="collapseReply"
                    {% if msg.msg_id %}
                        data-msg="{{ msg.msg_id }}" data-comment="{{ msg.pk }}"
                    {% else %}
                        data-msg="{{ msg.pk }}" data-comment=""
                    {% endif %}
                >reply</a>
            </span>
        {% endif %}
        <div class="comment-meta">
          <div class="collapse" id="reply_comment{{ msg|classname }}{{ msg.pk }}">
            {# reply form will be inserted here #}
          </div>
        </div>
    </div>

    <div class="msg_thread" id="collapse_thread{{ msg|classname }}{{ msg.pk }}">

      <div class="media-body">
        <!-- comment-meta -->
        {% for comment in comments %}
            {% render_msg comment comments_all.by_comment|get:comment.pk %}
        {% endfor %}
      </div>
    </div>
    <!-- comments -->

</div>